---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Hypervisor:
    - Proxmox:
        href: https://192.168.1.3:8006
        description: Proxmox
        siteMonitor: https://192.168.1.3:8006
        icon: proxmox       
        widget:
            type: proxmox
            url: https://192.168.1.3:8006
            username: user@pam!homelab
            password: 2756xxx
            node: pve-lab

- Monitoring:
    - Uptime Kuma:
        href: http://10.0.0.5:3001
        description: Uptime Kuma
        siteMonitor: http://10.0.0.5:3001
        icon: uptime-kuma
        widget:
            type: uptimekuma
            url: http://10.0.0.5:3001
            slug: all

- Infrastructure:
    - Portainer:
        href: https://192.168.1.15:9443
        description: Portainer
        siteMonitor: https://192.168.1.15:9443
        icon: portainer
        widget:
            type: portainer
            url: https://192.168.1.15:9443
            env: 2
            key: ptr_xxx

- Containers:
    - Docker:    
        href: 192.168.1.2:8080
        description: nginx
        server: docker
        container: web