---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Homelab Dashboard

background:
  image: /images/background.png
  blur: sm 
  saturate: 50 
  brightness: 50 
  opacity: 50 







